name: captcha_solver_flutter
"
"description: A Flutter application to solve captchas using ONNX Runtime.
"
"publish_to: 'none'

"
"version: 1.0.0+1

"
"environment:
"
"  sdk: '>=3.0.0 <4.0.0'

"
"dependencies:
"
"  flutter:
"
"    sdk: flutter
"
"  http: ^1.2.1
"
"  onnxruntime: ^1.4.1
"
"  image: ^4.1.7
"
"  cupertino_icons: ^1.0.6

"
"dev_dependencies:
"
"  flutter_test:
"
"    sdk: flutter
"
"  flutter_lints: ^3.0.0

"
"flutter:
"
"  uses-material-design: true
"
"  assets:
"
"    - assets/ml/holako_bag.onnx
