# Workflow name
name: Build Flutter APK

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main/master branches
  push:
    branches: [ main, master ] # Adjust branch names if needed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@v4

    # Sets up Java environment (required by Flutter for Android builds)
    - name: Set up Java JDK 17 
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # Or another distribution like 'zulu'
        java-version: '17' 

    # Sets up Flutter SDK
    - name: Set up Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0' # Specify desired Flutter version (check latest stable)
        channel: 'stable' # Or 'beta', 'dev', 'master'
        cache: true # Enable caching for faster builds

    # Get Flutter dependencies defined in pubspec.yaml
    - name: Get Flutter dependencies
      run: flutter pub get

    # Optional: Run code analysis
    # - name: Analyze project source
    #   run: flutter analyze

    # Optional: Run tests
    # - name: Run tests
    #   run: flutter test

    # Clean previous build artifacts (optional but good practice)
    - name: Clean Flutter build artifacts
      run: flutter clean

    # Build the Android APK (release mode)
    - name: Build Flutter APK (Release)
      run: flutter build apk --release --no-shrink # Add --no-shrink if you encounter issues with ONNX/R8

    # Upload the generated APK as a build artifact
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: flutter-app-apk 
        # Path to the APK file generated by Flutter
        path: build/app/outputs/flutter-apk/app-release.apk 
        # Optional: How long to retain the artifact (default is 90 days)
        # retention-days: 7
